import type { CSSProperties } from "react";

export type PageThemeType =
  | "salary-hourly"
  | "hourly-salary"
  | "salary-monthly"
  | "salary-biweekly"
  | "after-tax";

const PAGE_THEMES: Record<PageThemeType, CSSProperties> = {
  "salary-hourly": {
    "--accent-rgb": "96 165 250",
    "--accent-alt-rgb": "129 140 248",
    "--accent-soft-rgb": "56 189 248",
    "--bg-top": "#0b1324",
    "--bg-mid": "#081324",
    "--bg-bottom": "#050a16",
    "--glow-main-x": "9%",
    "--glow-main-y": "-8%",
    "--glow-main-size": "62% 40%",
    "--glow-main-opacity": "0.2",
    "--glow-alt-x": "80%",
    "--glow-alt-y": "2%",
    "--glow-alt-size": "40% 30%",
    "--glow-alt-opacity": "0.14",
    "--hero-highlight-opacity": "0.1",
    "--scene-separation": "0.22",
    "--glow-strength": "1.08",
    "--base-brightness": "0.032",
  } as CSSProperties,
  "hourly-salary": {
    "--accent-rgb": "34 211 238",
    "--accent-alt-rgb": "59 130 246",
    "--accent-soft-rgb": "6 182 212",
    "--bg-top": "#081728",
    "--bg-mid": "#061426",
    "--bg-bottom": "#030b17",
    "--glow-main-x": "4%",
    "--glow-main-y": "-10%",
    "--glow-main-size": "64% 40%",
    "--glow-main-opacity": "0.24",
    "--glow-alt-x": "79%",
    "--glow-alt-y": "8%",
    "--glow-alt-size": "36% 25%",
    "--glow-alt-opacity": "0.12",
    "--hero-highlight-opacity": "0.12",
    "--scene-separation": "0.24",
    "--glow-strength": "1.15",
    "--base-brightness": "0.038",
  } as CSSProperties,
  "salary-monthly": {
    "--accent-rgb": "99 102 241",
    "--accent-alt-rgb": "167 139 250",
    "--accent-soft-rgb": "129 140 248",
    "--bg-top": "#120f2a",
    "--bg-mid": "#0d1230",
    "--bg-bottom": "#080b1f",
    "--glow-main-x": "49%",
    "--glow-main-y": "-12%",
    "--glow-main-size": "72% 42%",
    "--glow-main-opacity": "0.18",
    "--glow-alt-x": "66%",
    "--glow-alt-y": "12%",
    "--glow-alt-size": "42% 30%",
    "--glow-alt-opacity": "0.11",
    "--hero-highlight-opacity": "0.09",
    "--scene-separation": "0.22",
    "--glow-strength": "1.02",
    "--base-brightness": "0.028",
  } as CSSProperties,
  "salary-biweekly": {
    "--accent-rgb": "168 85 247",
    "--accent-alt-rgb": "236 72 153",
    "--accent-soft-rgb": "139 92 246",
    "--bg-top": "#180f2c",
    "--bg-mid": "#130b24",
    "--bg-bottom": "#090613",
    "--glow-main-x": "5%",
    "--glow-main-y": "25%",
    "--glow-main-size": "48% 44%",
    "--glow-main-opacity": "0.22",
    "--glow-alt-x": "95%",
    "--glow-alt-y": "22%",
    "--glow-alt-size": "46% 40%",
    "--glow-alt-opacity": "0.18",
    "--hero-highlight-opacity": "0.12",
    "--scene-separation": "0.27",
    "--glow-strength": "1.14",
    "--base-brightness": "0.03",
  } as CSSProperties,
  "after-tax": {
    "--accent-rgb": "20 184 166",
    "--accent-alt-rgb": "15 118 110",
    "--accent-soft-rgb": "45 212 191",
    "--bg-top": "#071018",
    "--bg-mid": "#050a11",
    "--bg-bottom": "#02050a",
    "--glow-main-x": "46%",
    "--glow-main-y": "112%",
    "--glow-main-size": "68% 42%",
    "--glow-main-opacity": "0.11",
    "--glow-alt-x": "84%",
    "--glow-alt-y": "96%",
    "--glow-alt-size": "38% 28%",
    "--glow-alt-opacity": "0.07",
    "--hero-highlight-opacity": "0.05",
    "--scene-separation": "0.29",
    "--glow-strength": "0.84",
    "--base-brightness": "0.01",
  } as CSSProperties,
};

export const PAGE_IDENTITY_LABELS: Record<PageThemeType, string> = {
  "salary-hourly": "Salary to Hourly",
  "hourly-salary": "Hourly to Salary",
  "salary-monthly": "Salary to Monthly",
  "salary-biweekly": "Salary to Biweekly",
  "after-tax": "After-Tax by State",
};

export function getPageTheme(type: PageThemeType): CSSProperties {
  return PAGE_THEMES[type];
}
