import type { CSSProperties } from "react";

export type PageThemeType =
  | "salary-hourly"
  | "hourly-salary"
  | "salary-monthly"
  | "salary-biweekly"
  | "after-tax";

const PAGE_THEMES: Record<PageThemeType, CSSProperties> = {
  "salary-hourly": {
    "--accent-rgb": "67 97 238",
    "--accent-alt-rgb": "59 130 246",
    "--accent-soft-rgb": "129 140 248",
    "--bg-top": "#0f1739",
    "--bg-mid": "#0b1431",
    "--bg-bottom": "#070c1f",
    "--glow-main-x": "14%",
    "--glow-main-y": "-8%",
    "--glow-main-size": "62% 38%",
    "--glow-main-opacity": "0.22",
    "--glow-alt-x": "86%",
    "--glow-alt-y": "8%",
    "--glow-alt-size": "44% 32%",
    "--glow-alt-opacity": "0.16",
    "--hero-highlight-opacity": "0.12",
    "--scene-separation": "0.24",
    "--glow-strength": "1.1",
    "--base-brightness": "0.036",
    "--surface-tint": "0.18",
    "--surface-tint-strong": "0.26",
    "--surface-alt-tint": "0.14",
    "--table-tint": "0.18",
  } as CSSProperties,
  "hourly-salary": {
    "--accent-rgb": "34 211 238",
    "--accent-alt-rgb": "14 165 233",
    "--accent-soft-rgb": "56 189 248",
    "--bg-top": "#082134",
    "--bg-mid": "#071c2d",
    "--bg-bottom": "#04111d",
    "--glow-main-x": "5%",
    "--glow-main-y": "-10%",
    "--glow-main-size": "64% 40%",
    "--glow-main-opacity": "0.24",
    "--glow-alt-x": "78%",
    "--glow-alt-y": "8%",
    "--glow-alt-size": "40% 30%",
    "--glow-alt-opacity": "0.15",
    "--hero-highlight-opacity": "0.13",
    "--scene-separation": "0.25",
    "--glow-strength": "1.14",
    "--base-brightness": "0.038",
    "--surface-tint": "0.2",
    "--surface-tint-strong": "0.28",
    "--surface-alt-tint": "0.16",
    "--table-tint": "0.2",
  } as CSSProperties,
  "salary-monthly": {
    "--accent-rgb": "99 102 241",
    "--accent-alt-rgb": "79 70 229",
    "--accent-soft-rgb": "167 139 250",
    "--bg-top": "#16153a",
    "--bg-mid": "#121433",
    "--bg-bottom": "#090a22",
    "--glow-main-x": "52%",
    "--glow-main-y": "-12%",
    "--glow-main-size": "72% 42%",
    "--glow-main-opacity": "0.2",
    "--glow-alt-x": "72%",
    "--glow-alt-y": "10%",
    "--glow-alt-size": "44% 32%",
    "--glow-alt-opacity": "0.14",
    "--hero-highlight-opacity": "0.11",
    "--scene-separation": "0.24",
    "--glow-strength": "1.06",
    "--base-brightness": "0.032",
    "--surface-tint": "0.19",
    "--surface-tint-strong": "0.27",
    "--surface-alt-tint": "0.16",
    "--table-tint": "0.19",
  } as CSSProperties,
  "salary-biweekly": {
    "--accent-rgb": "192 38 211",
    "--accent-alt-rgb": "168 85 247",
    "--accent-soft-rgb": "236 72 153",
    "--bg-top": "#211137",
    "--bg-mid": "#1a0d2f",
    "--bg-bottom": "#0d0618",
    "--glow-main-x": "8%",
    "--glow-main-y": "20%",
    "--glow-main-size": "50% 46%",
    "--glow-main-opacity": "0.24",
    "--glow-alt-x": "94%",
    "--glow-alt-y": "24%",
    "--glow-alt-size": "48% 40%",
    "--glow-alt-opacity": "0.18",
    "--hero-highlight-opacity": "0.14",
    "--scene-separation": "0.27",
    "--glow-strength": "1.16",
    "--base-brightness": "0.034",
    "--surface-tint": "0.22",
    "--surface-tint-strong": "0.3",
    "--surface-alt-tint": "0.18",
    "--table-tint": "0.21",
  } as CSSProperties,
  "after-tax": {
    "--accent-rgb": "16 185 129",
    "--accent-alt-rgb": "5 150 105",
    "--accent-soft-rgb": "45 212 191",
    "--bg-top": "#071513",
    "--bg-mid": "#06110f",
    "--bg-bottom": "#030807",
    "--glow-main-x": "46%",
    "--glow-main-y": "112%",
    "--glow-main-size": "66% 40%",
    "--glow-main-opacity": "0.13",
    "--glow-alt-x": "88%",
    "--glow-alt-y": "96%",
    "--glow-alt-size": "40% 30%",
    "--glow-alt-opacity": "0.1",
    "--hero-highlight-opacity": "0.08",
    "--scene-separation": "0.3",
    "--glow-strength": "0.9",
    "--base-brightness": "0.012",
    "--surface-tint": "0.18",
    "--surface-tint-strong": "0.24",
    "--surface-alt-tint": "0.14",
    "--table-tint": "0.18",
  } as CSSProperties,
};

export const PAGE_IDENTITY_LABELS: Record<PageThemeType, string> = {
  "salary-hourly": "Salary to Hourly",
  "hourly-salary": "Hourly to Salary",
  "salary-monthly": "Salary to Monthly",
  "salary-biweekly": "Salary to Biweekly",
  "after-tax": "After-Tax by State",
};

export function getPageTheme(type: PageThemeType): CSSProperties {
  return PAGE_THEMES[type];
}
